language: python

notifications:
  email:
    - ted@disqus.com

python:
    - "2.6"
    - "2.7"
    - "3.4"

env:
    - DJANGO='Django==1.5.*'
    - DJANGO='Django==1.6.*'
    - DJANGO='Django==1.7.*'
    - DJANGO='Django==1.8.*'
    - DJANGO='Django==1.9.*'
    - DJANGO='Django==1.10.*'

matrix:
    exclude:
        - env: DJANGO='Django==1.7.*'
          python: "2.6"
        - env: DJANGO='Django==1.8.*'
          python: "2.6"
        - env: DJANGO='Django==1.9.*'
          python: "2.6"
        - env: DJANGO='Django==1.10.*'
          python: "2.6"

install:
    - pip install $DJANGO

script: make test
